---
title: "MMF Auswertung"
author: "Lola Schiel"
date: "8 1 2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Daten einlesen

#Daten werden in zwei Versionen eingelesen, einmal mit der 99 als "Keine Angabe" und einmal als NA bei "Keine Angabe". Das hat den Hintergrund, dass mit der 99 die nicht vorhandenen Angaben mit zu der Gesamtheit zählen, während sie bei NA herausgerechnet werden. Die Datensätze mit NA haben die Endung _na. 


```{r}
alles <- read.csv("https://raw.githubusercontent.com/lolaschiel/MMF-Spendenbereitschaft/main/data.csv", header=TRUE, sep=";")
alles_na <- alles
alles_na[alles_na=="99"] <- NA


savethechildren <- subset(alles, organisation==1)
savethechildren_na <- savethechildren
savethechildren_na[savethechildren_na=="99"] <- NA

greenpeace <- subset(alles, organisation==2)
greenpeace_na <- greenpeace
greenpeace_na[greenpeace_na=="99"] <- NA

bund <- subset(alles, organisation==3)
bund_na <- bund
bund_na[bund_na=="99"] <- NA

bvhk <- subset(alles, organisation==4)
bvhk_na <- bvhk
bvhk_na[bvhk_na=="99"] <- NA

wwf <- subset(alles, organisation==5)
wwf_na <- wwf
wwf_na[wwf_na=="99"] <- NA

caritas <- subset(alles, organisation==6)
caritas_na <- caritas
caritas_na[caritas_na=="99"] <- NA

plan <- subset(alles, organisation==7)
plan_na <- plan
plan_na[plan_na=="99"] <- NA

whh <- subset(alles, organisation==8)
whh_na <- whh
whh_na[whh_na=="99"] <- NA


alles
```

## Spalten: Anzahl (absolut)


```{r}
# Dieser Chuck gibt die Ergebnisse in absoluten Zahlen mit 2 Kommastellen wider.
# Nach dem Pfeil bei Datensatz trägt man den zur Analyse gewünschten Datensatz ein. Möchte man also die gesamte Stichprobe überprüfen, so schreibt man:
# datensatz <- gesamt
# Möchte man nur die Briefe von BUND analysieren, so schreibt man:
# datensatz <- bund

datensatz <- gesamt

for (col in 3:ncol(datensatz)) {

  print(colnames(datensatz)[col])
  table <- table(datensatz[,col])
  print(table)
  cat("\n\n")
}


```

## Spalten: Prozente (relativ)


```{r}
# Dieser Chuck gibt die Ergebnisse in Prozentangaben mit 2 Kommastellen wider.

datensatz <- gesamt

for (col in 3:ncol(datensatz)) {

  print(colnames(datensatz)[col])
  table <- round(prop.table(table(datensatz[,col])), digits=4)*100
  print(table)
  cat("\n\n")
}

```


